name: 'Amazon CodeArtifact Action for GitHub Actions'
description: 'Logs in the to one or more Amazon CodeArtifact registries'
branding:
  icon: 'cloud'
  color: 'orange'
author: "opzkit"

inputs:
  aws-region:
    description: 'AWS Region, e.g. us-east-2'
    required: false
    default: eu-west-1
  domain:
    description: CodeArtifact domain to which the package repository belongs
    required: true
  domain-owner:
    description: Owner (AWS Account) of the CodeArtifact domain
    required: true
  repository:
    description: CodeArtifact repository for which to optionally fetch the URL
    required: false
  tool:
    description: Format of the repository URL
    required: false
    default: npm

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOMAIN: ${{ inputs.domain }}
    DOMAIN_OWNER: ${{ inputs.domain-owner }}
    REPOSITORY: ${{ inputs.repository }}
    REGION: ${{ inputs.aws-region }}
    TOOL: ${{ inputs.tool }}
